version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: kidneycare_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kidney_care
      POSTGRES_DB: kidneycare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: kidneycare_cache
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: kidneycare_api
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:kidney_care@kidneycare_db/kidneycare
      REDIS_URL: redis://kidneycare_cache:6379
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  redis_data:
