# fly.toml app configuration file generated for backend-billowing-waterfall-4640 on 2025-04-08T04:38:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-billowing-waterfall-4640'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
